# Generated by Django 3.0.8 on 2020-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='newnote',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
